f=open("personal.txt","a")
a=input("enter a first name:")
b=input("enter a DOB:")
c=input("enter a course:")
d=input("enter a department:")
e=input("enter a college name:")
f=input("enter a place:")
g=input("enter a email:")
f.write("\n"+a+"\n"+b+"\n"+c+"\n"+d+"\n"+e+"\n"+f+"\n"+g)
f.close()
