name=['niki','dhanu','kar','bhav']
name2=['kavi','kavin']
print(name,name2)
print(type(name))
name.append('avina')
print(name)
name.extend(name2)
print(name)
name.insert(1,'jaya')
print(name)
name2.remove('kavi')
print(name2)
name.pop()
print(name)
print(name.index('avina'))
name.reverse()
print('reverse list:',name)
name.sort()
print(name)
name3=name.copy()
print('copied list',name3)
name3.clear()
print(name)
