f=open("our.txt","a")
a=input("enter a name:")
b=input("enter a age:")
c=input("enter a father name:")
d=input("enter a mother name:")
e=input("enter a language:")
f.write("\n"+a+"\n"+b+"\n"+c+"\n"+d+"\n"+e)
f.close()