#open("inter.txt","x")
#f=open("inter.txt","w")
#f=open("inter.txt","a")
#f.write("\nname\tag")
#f=open("inter.txt","r")
#a=f.read()
#print(a)
f=open("inter.txt","a")
a=input("enter a name:")
b=int(input("enter a age:"))
c=input("enter a class:")
d=input("enter a place:")
e=input("enter a rollno:")
f.close()
