from tkinter import*
from tkinter import ttk,font
def user_reg(k):
    k=Tk()
    k.geometry("1000x700")
    k.title("register")
    frame=Frame(k,width=1500,height=700,bg="white")
    frame.pack()
    label_font=font.Font(k,weight="bold",family="Time New Roman",size=20)
    l=Label(frame,text="User login",font=label_font,bg="pink")
    l.place(relx=0.45,rely=0.2)
    label_font=font.Font(k,weight="bold",family="Time New Roman",size=18)
    l=Label(frame,text="Name",font=label_font,bg="skyblue")
    l.place(relx=0.37,rely=0.4)
    l=Label(frame,text="Age",font=label_font,bg="skyblue")
    l.place(relx=0.37,rely=0.5)
    l=Label(frame,text="Qualification",font=label_font,bg="skyblue")
    l.place(relx=0.37,rely=0.6)
    l=Label(frame,text="Email",font=label_font,bg="skyblue")
    l.place(relx=0.37,rely=0.7)
    l1=Entry(frame)
    l1.place(relx=0.50,rely=0.4)
    l2=Entry(frame)
    l2.place(relx=0.50,rely=0.5)
    l3=Entry(frame)
    l3.place(relx=0.50,rely=0.6)
    l4=Entry(frame)
    l4.place(relx=0.50,rely=0.7)
    b=Button(k,text="Submit",font=label_font,bg="grey",command=lambda:file(l1.get(),l2.get(),l3.get(),l4.get(),k))
    b.place(relx=0.53,rely=0.7)

def file(a,b,c,d,k):
    t=a+" "+b+" "+c+" "+d+" "+"\n"
    f=open("reg.txt","a")
    f.write(t)
def home():
    k=Tk()
    k.geometry("1500x700")
    frame=Frame(k,width=1500,height=50,bg="pink")
    frame.pack()
    label_font=font.Font(weight="bold",family="time new roman",size=20)
    x=Label(frame,text="Register",font=label_font)
    x.config(bg="yellow")
    x.place(relx=0.45,rely=0.1)
    d1=Label(k,text="Username",font=label_font,bg="lightgreen")
    d1.place(relx=0.31,rely=0.4)
    d2=Label(k,text="Password",font=label_font,bg="lightgreen")
    d2.place(relx=0.31,rely=0.5)
    v1=Entry(k)
    v1.place(relx=0.54,rely=0.41)
    v2=Entry(k)
    v2.place(relx=0.54,rely=0.51)
    b=Button(k,text="Login",font=label_font,bg="grey",command=lambda:user_reg(k))
    b.place(relx=0.56,rely=0.61)
    frame=Frame(k,width=1500,height=40,bg="pink")
    frame.pack()
    frame.place(relx=0.0,rely=0.94)
    k.mainloop()
home()    