import tkinter
from tkinter import*
from tkinter import ttk,font,messagebox
root=Tk()
root.title("Bank")
root.geometry("1500x1500")
root.attributes('-fullscreen',True)
frame=Frame(root,width=10000,height=60,bg="pink")
frame.pack()

def Stu_reg(root):
    root.destroy()
    root = Tk()
    root.geometry("1500x700")
    root.title("CITY UNION BANK")
label_font = font.Font(weight="bold", family="Times New Roman", size=20)
x=Label(frame, text="NAME:",bg="red")
x.place(relx=0.05,rely=0.23)
x=Label(frame,text="AGE:",bg="red")
x.place(relx=0.05,rely=0.32)
x=Label(frame,text="FATHER NAME:",bg="red")
x.place(relx=0.05,rely=0.43)
x=Label(frame,text="MOTHER NAME:",bg="red")
x.place(relx=0.05,rely=0.54)
x=Label(frame,text="ADDRESS",bg="red")
x.place(relx=0.05,rely=0.65)
b=Button(frame,text="bold",bg="yellow")
b.place(relx=0.14,rely=0.85)
x1=Entry(frame)
x1.place(relx=0.17,rely=0.24)
x2=Entry(frame)
x2.place(relx=0.17,rely=0.33)
x3=Entry(frame)
x3.place(relx=0.17,rely=44)
x4=Entry(frame)
x4.place(relx=0.17,rely=0.55)
x5=Entry(frame)
x5.place(relx=0.17,rely=0.66)
b=Button(frame,text="student",font=label_font,command=lambda:Stu_reg(x1.get(),x2.get(),x3.reg(),x4.reg(),x5.reg()))
b.place(relx=0.47,rely=0.82)
frame.pack()
root.mainloop()


label_font=font.Font(weight="bold",family="Times New Roman",size=20)
x=Label(frame,text="CUB BANK",font=label_font)
x.config(bg="black", fg= "white")
x.place(relx=0.43,rely=0.01)
frame=Frame(root,width=15000,height=15000,bg="violet")
frame.pack()
frame.place(relx=0.1,rely=0.4)
label_font=font.Font(weight="bold",family="Times New Roman",size=20)
x=Label(frame,text="Student number",font=label_font)
x.config(bg= "pink")
label_font=font.Font(weight="bold",family="Times New Roman",size=20)
a=Label(frame,text="Student number:",font=label_font)
a.place(relx=0.1,rely=0.5)
a.config(bg= "yellow")
b=Label(frame,text="Student login:",font=label_font)
b.place(relx=0.8,rely=0.5)
b.config(bg= "yellow")
label_font=font.Font(weight="bold",family="Times New Roman",size=20)
a=Label(frame,text="Student Registration:",font=label_font)
a.place(relx=0.4,rely=0.3)
a.config(bg="yellow")
frame.pack()
root.mainloop()
a1=Entry(frame)
a1.place(relx=0.5,rely=0.42, width=200, height=25)
b1=Entry(frame,show="*")
b1.place(relx=0.5,rely=0.57, width=200, height=25)
b5=Button(frame,text="Student Registration",font=label_font,command=lambda:Stu_reg(a1.get(),b1.get(),root))
b5.place(relx=0.3,rely=0.8)
frame=Frame(root,width=1500,height=50,bg="blue")
frame.pack()
frame.place(relx=0.0,rely=0.94)
label_font=font.Font(weight="bold",family="Times New Roman",size=20)
x=Label(frame,text="Copyright © 2024 CUB ",font=label_font,bg="Red")
x.config(bg= "blue", fg= "white")
x.place(relx=0.35,rely=0.1)
frame.pack()
root.mainloop()


x.config(bg="blue", fg="white")
x.place(relx=0.43, rely=0.01)
label_font = font.Font(weight="bold", family="Times New Roman", size=20)
k="""The first branch bank was opened at mannargudi on 24th jan 1930,
the one of the branch was opened at nagapattinam,mayiladuthurai,porayar. 
The bank included in the second scheduled in the reserve bank of india act,1985"""
l = Label(root, text=k, font=label_font)
l.place(relx=0.1, rely=0.1)
frame = Frame(root)
frame.pack()
frame.place(relx=0.4, rely=0.4)


tree = ttk.Treeview(frame, columns=("IFSC code", "Name", "Age", "Balance"), display="headings")
tree.heading("IFSC code", text="IFSC code")
tree.heading("Name", text="Name")
tree.heading("Age", text="Age")
tree.heading("Balance", text="Balance")
tree.pack()
frame1=Frame(root,width=250, height=270, bg="gray")
frame1.pack()
frame1.place(relx=0.1, rely=0.42)
label_font=font.Font(weight="bold",family="Times New Roman",size=10)
x=Label(frame1,text="STUDENTREGISTRATION",font=label_font, bg="gray")
x.place(relx=0.35,rely=0.01)
a=Label(frame1,text="Customer Name:",font=label_font, bg="gray")
a.place(relx=0.01,rely=0.2)
b=Label(frame1,text="Customer Id:",font=label_font, bg="gray")
b.place(relx=0.01,rely=0.3)
c=Label(frame1,text="Amount Deposit:",font=label_font, bg="gray")
c.place(relx=0.01,rely=0.4)
a1=Entry(frame1)
a1.place(relx=0.5,rely=0.2)
b1=Entry(frame1)
b1.place(relx=0.5,rely=0.3)
c1=Entry(frame1)
c1.place(relx=0.5,rely=0.4)
label_font=font.Font(weight="bold",family="Times New Roman",size=25)
b=Button(frame1,text="Registration",font=label_font,command=lambda:Stu_reg(a1.get(),b1.get(),c1.get()))
b.place(relx=0.35,rely=0.5)
root.mainloop()










